### ISSUE TITLE
Deployment of MLFlow model FAILED

### ISSUE THREAD

**Issue by michalmar** [MicrosoftLearning/mslearn-aml-cli#1]
# Module: 05
## Lab/Demo: 05

Description of issue

I am having troubles deploying to managed endpoint (CLIv2) from this tutorial, lab 5 : [mslearn-aml-cli (microsoftlearning.github.io)](https://microsoftlearning.github.io/mslearn-aml-cli/Instructions/Labs/05-deploy-managed-endpoint.html). It keeps failing on  deployment (resource not ready). I have model trained using MLFlow format, score script and env is generated automatically. After some digging this is the error thrown during deployment:

```
ERROR: Could not find a version that satisfies the requirement sanic~=21.6.0 (from azureml-inference-server-http) (from versions: 0.1.0, 0.1.1, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.4, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 18.12.0, 19.3.1, 19.6.0, 19.6.2, 19.6.3, 19.9.0, 19.12.0, 19.12.2, 19.12.3, 19.12.4, 19.12.5, 20.3.0, 20.6.0, 20.6.1, 20.6.2, 20.6.3, 20.9.0, 20.9.1, 20.12.0, 20.12.1, 20.12.2, 20.12.3, 20.12.4, 20.12.5, 20.12.6)
ERROR: No matching distribution found for sanic~=21.6.0
Error occurred. Sleeping to send error logs.
```
Repro steps:

Follow Lab 5

**Comment by madiepev** [comment]
@michalmar issue should be fixed now. Please open a new issue if you still face problems.

**Comment by michalmar** [comment]
@madiepev and what should I do to see the fix? should I pull changes in the repo and rerun?
