### ISSUE TITLE
Lab5 Creating Pipeline Job Failed

### ISSUE THREAD

**Issue by HeZhang33** [MicrosoftLearning/mslearn-aml-cli#2]
# Module: 05
#### Step: 04

Description of issue

Failed on step "az ml job create --file ./mslearn-aml-cli/Allfiles/Labs/05/job.yml" (already putting my own compute instance as instructed, but still failed). Errors as below:

FAREAST+zhanghe@cn-zhanghe MINGW64 ~/Desktop/mslearn-aml-cli/Allfiles/Labs/05 (master)
$ az ml job create --file job.yml
ERROR: Met error <class 'marshmallow.exceptions.ValidationError'>:Validation for PipelineJobSchema failed:

 {
  "jobs": {
    "stats_job": {
      "value": [
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./summary-stats.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./summary-stats.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "code": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide the correct registry path prefixed with 'azureml://':\n"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/codes/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
                  ]
                },
                {
                  "_schema": [
                    "Not a valid URL."
                  ]
                },
                {
                  "_schema": [
                    "Not a valid string."
                  ]
                }
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ]
        },
        {
          "objective": [
            "Missing data for required field."
          ],
          "limits": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['sweep']"
          ],
          "trial": [
            "Missing data for required field."
          ]
        },
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./summary-stats.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./summary-stats.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "type": [
                "Value command passed is not in set ['parallel']"
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        },
        {
          "command": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ],
          "component": [
            "Unknown field."
          ]
        },
        {
          "null": [
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ]
            }
          ]
        },
        {
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        }
      ]
    },
    "fix_missing_job": {
      "value": [
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./fix-missing-data.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./fix-missing-data.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "code": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide the correct registry path prefixed with 'azureml://':\n"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/codes/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
                  ]
                },
                {
                  "_schema": [
                    "Not a valid URL."
                  ]
                },
                {
                  "_schema": [
                    "Not a valid string."
                  ]
                }
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ]
        },
        {
          "objective": [
            "Missing data for required field."
          ],
          "limits": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['sweep']"
          ],
          "trial": [
            "Missing data for required field."
          ]
        },
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./fix-missing-data.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./fix-missing-data.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "type": [
                "Value command passed is not in set ['parallel']"
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        },
        {
          "command": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ],
          "component": [
            "Unknown field."
          ]
        },
        {
          "null": [
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ]
            }
          ]
        },
        {
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        }
      ]
    },
    "normalize_job": {
      "value": [
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./normalize-data.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./normalize-data.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "code": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide the correct registry path prefixed with 'azureml://':\n"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/codes/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
                  ]
                },
                {
                  "_schema": [
                    "Not a valid URL."
                  ]
                },
                {
                  "_schema": [
                    "Not a valid string."
                  ]
                }
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ]
        },
        {
          "objective": [
            "Missing data for required field."
          ],
          "limits": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['sweep']"
          ],
          "trial": [
            "Missing data for required field."
          ]
        },
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./normalize-data.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./normalize-data.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "type": [
                "Value command passed is not in set ['parallel']"
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        },
        {
          "command": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ],
          "component": [
            "Unknown field."
          ]
        },
        {
          "null": [
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ]
            }
          ]
        },
        {
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        }
      ]
    },
    "train_job": {
      "value": [
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./train-decision-tree.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./train-decision-tree.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "code": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'collections.OrderedDict'>: OrderedDict([('local_path', './src')])"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide the correct registry path prefixed with 'azureml://':\n"
                  ]
                },
                {
                  "_schema": [
                    "In order to specify an existing codes, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/codes/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
                  ]
                },
                {
                  "_schema": [
                    "Not a valid URL."
                  ]
                },
                {
                  "_schema": [
                    "Not a valid string."
                  ]
                }
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ]
        },
        {
          "objective": [
            "Missing data for required field."
          ],
          "limits": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['sweep']"
          ],
          "trial": [
            "Missing data for required field."
          ]
        },
        {
          "component": [
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./train-decision-tree.yml"
              ]
            },
            {
              "_schema": [
                "Value passed is not a data binding string: <class 'str'>: file:./train-decision-tree.yml"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing None, please provide the correct registry path prefixed with 'azureml://':\n"
              ]
            },
            {
              "_schema": [
                "In order to specify an existing components, please provide either of the following prefixed with 'azureml:':\n1. The full ARM ID for the resource, e.g.azureml:/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>/components/<resource_name>/<version-if applicable>)\n2. The short-hand name of the resource registered in the workspace, eg: azureml:<short-hand-name>:<version-if applicable>. For example, version 1 of the environment registered as 'my-env' in the workspace can be referenced as 'azureml:my-env:1'"
              ]
            },
            {
              "type": [
                "Value command passed is not in set ['parallel']"
              ]
            },
            {
              "_schema": [
                "Not supporting non file for component"
              ]
            }
          ],
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        },
        {
          "command": [
            "Missing data for required field."
          ],
          "type": [
            "Value component passed is not in set ['command']"
          ],
          "component": [
            "Unknown field."
          ]
        },
        {
          "null": [
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "target_column_name": [
                "Missing data for required field."
              ],
              "task": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ],
              "target_column_name": [
                "Missing data for required field."
              ]
            },
            {
              "type": [
                {
                  "_schema": [
                    "Value passed is not a data binding string: <class 'str'>: component"
                  ]
                },
                {
                  "_schema": [
                    "Value component passed is not in set ['automl']"
                  ]
                }
              ],
              "task": [
                "Missing data for required field."
              ]
            }
          ]
        },
        {
          "type": [
            "Value component passed is not in set ['parallel']"
          ]
        }
      ]
    }
  },
  "inputs": [
    {
      "pipeline_job_input": [
        "Unknown field."
      ]
    },
    {
      "pipeline_job_input": {
        "value": [
          {
            "dataset": [
              "Unknown field."
            ]
          },
          {
            "dataset": [
              "Unknown field."
            ],
            "mode": [
              "Unknown field."
            ]
          },
          {
            "_schema": [
              "Not a valid integer."
            ]
          },
          {
            "_schema": [
              "Not a valid string."
            ]
          },
          {
            "_schema": [
              "Not a valid boolean."
            ]
          },
          {
            "_schema": [
              "Not a valid number."
            ]
          }
        ]
      }
    }
  ]
}

 If you are trying to configure a job that is not of type pipeline, please specify the correct job type in the 'type' property.
For a more detailed breakdown of the PipelineJob schema, please see: https://aka.ms/ml-cli-v2-job-pipeline-yaml-reference.
The easiest way to author a specification file is using IntelliSense and auto-completion Azure ML VS code extension provides: https://code.visualstudio.com/docs/datascience/azure-machine-learning
To set up: https://docs.microsoft.com/azure/machine-learning/how-to-setup-vs-code
Please check log in debug mode for more details.

**Comment by madiepev** [comment]
@HeZhang33 thanks for reporting the issue. The lab files have been updated to work with the latest AML CLI version. Feel free to open a new issue if you still encounter problems.

**Comment by HeZhang33** [comment]
Thank you for the feedback! I just tried the updated code, and the problem was solved indeed. Thanks a lot! @madiepev
