### ISSUE TITLE
Lab 5 Designer Failed: Can not find the diabetes-data from Datasets section  

### ISSUE THREAD

**Issue by HeZhang33** [MicrosoftLearning/mslearn-aml-cli#3]
# Module: 05
#### Step: 05: In the left menu, expand the Datasets section.

Description of issue
Hello,

I can not find the "diabetes-data" component in Datasets section of the Designer. In fact, there is no section called "Datasets" to expand anymore. I only see "Data" section, under which there is no "diabetes-data" either. Please advise! Thanks again!

Br, He Zhang

Repro steps:

1.
1.
1.

**Comment by madiepev** [comment]
The UI has changed and I've changed the instructions accordingly. Hopefully should fix the issue so closing it for now. Feel free to respond or create a new issue if there still is an issue.
