### ISSUE TITLE
Issue testing endpoint in lab 04 - 

### ISSUE THREAD

**Issue by Typod01** [MicrosoftLearning/mslearn-aml-cli#4]
# Module: Deploy a model to a managed online endpoint
#### Step: 

Description of issue
When running the online-endpoint invoke command I receive the following error

cli.azure.cli.core.azclierror: Met error <class 'Exception'>:Invalid input format: expected an array of items.
Please check log by running the command with '--debug' for more details.
az_command_data_logger: Met error <class 'Exception'>:Invalid input format: expected an array of items.
Please check log by running the command with '--debug' for more details.

Repro steps:

Run -  az ml online-endpoint invoke --name diabetes-mlflow --request-file ./mslearn-aml-cli/Allfiles/Labs/04/mlflow-endpoint/sample-data.json

**Comment by madiepev** [comment]
@Typod01 Could you be more specific? I don't think lab 4 includes a step that says to use `az ml online-endpoint invoke`? And the lab about online endpoints uses an endpoint with a different name?

**Comment by Typod01** [comment]
Hi, here are some more details.  the link to the content is - https://microsoftlearning.github.io/mslearn-aml-cli/Instructions/Labs/05-deploy-managed-endpoint.html

but the command refers to lab04 files:
az ml online-endpoint invoke --name diabetes-mlflow --request-file ./mslearn-aml-cli/Allfiles/Labs/04/mlflow-endpoint/sample-data.json

**Comment by madiepev** [comment]
Thanks. We'll review the labs and get back to you with a resolution.

**Comment by madiepev** [comment]
We've updated the labs to fix some issues. I'm closing this for now. Please let us know if you're still experiencing some issues.
