### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by Typod01** [MicrosoftLearning/mslearn-aml-cli#5]
# Module: 00
#### Step: 00

Description of issue
When running the following command i received a missing module error and the http endpoint never became available.  This w as resolved by adding the following line to the conda.yaml file of the sample-mlflow-sklearn-model

  - azureml-inference-server-http

**Comment by madiepev** [comment]
@Typod01 could you be more specific? Which lab, which step, and which command?

**Comment by Typod01** [comment]
on https://microsoftlearning.github.io/mslearn-aml-cli/Instructions/Labs/05-deploy-managed-endpoint.html

the following command failed:

 az ml online-deployment create --name mlflow-deployment --endpoint diabetes-mlflow -f ./mslearn-aml-cli/Allfiles/Labs/04/mlflow-endpoint/mlflow-deployment.yml --all-traffic

I received a 502 error and the deployment logs that the probe was unavailable and it stated a module was missing azureml-inference-server-http.

I edited the conda.yaml file on the endpoint created in the previous step , and added the line mentioned above, after that the command completed.  I will deploy again and get the exact error and post below.

**Comment by madiepev** [comment]
We've updated the labs to fix some issues. I'm closing this for now. Please let us know if you're still experiencing some issues.
